services:
  - type: web
    name: Astradio
    env: node
    plan: free
    region: oregon
    autoDeploy: true
    rootDir: .
    buildCommand: |
      corepack enable
      pnpm install --frozen-lockfile
      pnpm -w build
    startCommand: node apps/api/dist/app.js
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: 20.19.4