services:
  - type: web
    name: astradio-api
    env: node
    rootDir: .
    buildCommand: corepack enable && pnpm -w install --frozen-lockfile && pnpm --filter api build
    startCommand: node apps/api/dist/app-minimal.js
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: FRONTEND_URL
        sync: false
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000