services:
  - type: web
    name: Astradio
    env: node
    rootDir: .
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: node apps/api/dist/app-minimal.js
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: FRONTEND_URL
        sync: false
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000