name: Deploy Astradio

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm'
        cache-dependency-path: pnpm-lock.yaml
        
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
        
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      
    - name: Build monorepo
      run: pnpm build
      
    - name: Run smoke test
      run: |
        # Start API server in background
        pnpm --filter api dev &
        API_PID=$!
        
        # Wait for server to start
        sleep 10
        
        # Run smoke test
        node scripts/smoke.js
        
        # Stop API server
        kill $API_PID
        
    - name: Deploy API to Render
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        RENDER_SERVICE_NAME: ${{ secrets.RENDER_SERVICE_NAME || 'astradio-api' }}
      run: |
        # Use the existing Render deployment script
        node scripts/renderDeploy.js
        
    - name: Deploy Web to Vercel
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        working-directory: ./apps/web
        vercel-args: '--prod'
        
    - name: Update environment variables
      run: |
        # Update Vercel environment variables to point to the new API URL
        # This step ensures the frontend knows where to find the backend
        echo "API deployment completed. Frontend should now be connected to the backend."
        
    - name: Verify deployment
      run: |
        echo "✅ Deployment completed successfully!"
        echo "Backend: https://astradio-api.onrender.com"
        echo "Frontend: https://astradio.vercel.app" 